
<!-- START: iCal Event List ITEM -->
	<li class="iCalEventsItem">
		{EVENTLIST_ITEM_DATE_START_TPL}
		{EVENTLIST_ITEM_TIME_START_TPL}
		{EVENTLIST_ITEM_DATE_END_TPL}
		{EVENTLIST_ITEM_TIME_END_TPL}
		{EVENTLIST_ITEM_SUMMARY_TPL}
		{EVENTLIST_ITEM_DESCRIPTION_TPL}
		{EVENTLIST_ITEM_LOCATION_TPL}
		{EVENTLIST_ITEM_URL_TPL}
	</li>
<!-- END: iCal Event List ITEM -->
